name: Chouseisan Auto

on:
  schedule:
    - cron: "0 22 * * 0"  # 毎週日曜22:00（UTC）= 日本時間 月曜7:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-puppeteer-

      - run: npm install

      - run: node index.js
        env:
          CS_EMAIL: ${{ secrets.CS_EMAIL }}
          CS_PASSWORD: ${{ secrets.CS_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
